version: '3.7'

services:

  api:
    container_name: flask-container
    build:
      context: ./backend
      dockerfile: Dockerfile.api
    entrypoint: python run.py
    env_file:
      - backend/.env
    depends_on:
      - mongodb
    ports:
    - '5000:5000'
    networks:
      - backend_dev

  mongodb:
    container_name: mongo-container
    build:
      context: ./mongodb
      dockerfile: Dockerfile.mongo
    restart: always
    volumes:
      - ./mongodb/data:/data/db
    env_file:
      - backend/.env
    networks:
      - backend_dev


networks:

  backend_dev:
    driver: bridge
    