# Dockerfile for Flask auth API

FROM python:3.9-slim-bullseye
RUN /usr/local/bin/python -m pip install --upgrade pip

WORKDIR /app

COPY ./requirements.txt ./
RUN pip install -r ./requirements.txt

COPY . ./

EXPOSE 5000
CMD ["gunicorn", "-b", ":5000", "run:app"]
